- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      environment:
        http_proxy: http://172.30.155.180:3128
        https_proxy: https://172.30.155.180:3128
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: prateekg
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/prateekg/.kube/config
        remote_src: yes
        owner: prateekg

    - name: install Pod network
      become: yes
      become_user: prateekg
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      environment:
        http_proxy: http://172.30.155.180:3128
        https_proxy: https://172.30.155.180:3128
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
